### ISSUE TITLE
Code stuck in the init function ism330dhcx_sensor_acquisition_init()

### ISSUE THREAD

**Issue by chen694** [stm32duino/ISM330DHCX#11]
Thank you for providing this library which allows me communicate with the ISM330DHCX on my PWA, running with XMC4700.

The only issue I have encountered so far is with the initialization function ism330dhcx_sensor_acquisition_init(), sometimes (about 1 out of 10 power cycles) the device ID check fails, causing the code to get stuck in the while(1) loop which in turn triggers the watchdog reset of my system, please see the snapshot of the code below.
Could you advise on how to resolve this issue? Thank you!

/* Wait sensor boot time */
  platform_delay(BOOT_TIME);
	
  // Check device ID 
  ism330dhcx_device_id_get(&dev_ctx, &whoamI);

  if (whoamI != ISM330DHCX_ID)
   while (1);

**Comment by cparata** [comment]
Hi @chen694 ,
which bus are you using? I2C or SPI? Could you give more information about your hardware setup?
Best Regards,
Carlo

**Comment by fpistm** [comment]
Closed as no enough input from OP and no feedback.
