### ISSUE TITLE
add example with FIFO?

### ISSUE THREAD

**Issue by jerabaul29** [stm32duino/ISM330DHCX#6]
Hi,

First, many thanks for an awesome library :) . I have been using the Adafruit library so far to talk to the ISM330DHCX, but this library feels much more straightforward and looks much cleaner when reading it, so very much keen on changing to it :) .

Would it be possible to have an example of how to use the FIFO to get ACC and GYR output? Basically something that shows how to:

- set up the 6dof with the parameters one needs
- start the fifo output
- show how to read the full fifo to a bugger (I will time the reading with a timer myself, but this is not very relevant, I guess in the example just adding some delay to put a bit of space between the readings should be enough :) ).

**Comment by cparata** [comment]
Hi @jerabaul29 ,
FIFO example has been added into the library.
I close this issue.
Best Regards,
Carlo

**Comment by jerabaul29** [comment]
Amazing, many thanks :)
