### ISSUE TITLE
Example about interrupts (e.g. due to single tap detection)

### ISSUE THREAD

**Issue by iSpartaco** [stm32duino/ISM330DHCX#9]
Hello,

I would like to know more on how to use this library to send interrupts due to any detections such as signle tap or value over a threshold. This could be a good additions in examples list.

Thank you

**Comment by cparata** [comment]
Hi @iSpartaco ,
you can find all the examples for the interrupts of ISM330DHCX sensor in the [X-NUCLEO-IKS02A1 library](https://github.com/stm32duino/X-NUCLEO-IKS02A1/tree/main/examples).
Best Regards,
Carlo

**Comment by fpistm** [comment]
Closed as answered.
